SELECT FIRST_NAME, LAST_NAME, SALARY FROM employees;

SELECT DISTINCT (JOB_ID) FROM employees;

SELECT * FROM employees
WHERE SALARY > 10000;

SELECT DEPARTMENT_NAME FROM departments;

SELECT COUNTRY_NAME FROM countries
WHERE region_id = 3;

SELECT EMPLOYEE_ID FROM employees
WHERE COMMISSION_PCT IS NOT NULL;

SELECT LAST_NAME, SALARY, DEPARTMENT_ID FROM employees
WHERE SALARY BETWEEN 5000 and 10000;

SELECT DISTINCT CITY a FROM LOCATIONS a
JOIN
DEPARTMENTS b ON a.LOCATION_ID = b.LOCATION_ID; 

SELECT FIRST_NAME, COUNT (b.EMPLOYEE_ID) a FROM employees a
JOIN JOB_HISTORY b ON a.EMPLOYEE_ID = b.EMPLOYEE_ID
WHERE b.START_DATE > TO_DATE ('01-01-2001', 'DD-MM-YYYY');

SELECT DEPARTMENT_NAME a, COUNT (b.EMPLOYEE_ID) FROM DEPARTMENTS a
FULL JOIN EMPLOYEES b ON a.MANAGER_ID = b.MANAGER_ID
GROUP BY DEPARTMENT_NAME;

SELECT LAST_NAME a, DEPARTMENT_NAME b FROM EMPLOYEES a
JOIN DEPARTMENTS b ON a.MANAGER_ID = b.MANAGER_ID

SELECT EMPLOYEE_ID, SALARY FROM employees
WHERE SALARY > 
(SELECT AVG (SALARY) FROM employees);

